//lexem type, ID, keyword

LEXEM(ADD , "+")
LEXEM(SUB , "-")
LEXEM(LR, ";")
LEXEM(EQ, "=")
LEXEM(MUL, "\\cdot")
LEXEM(DIV, "/")
LEXEM(COMMA, ",")
LEXEM(LBRACKET_ROUND, "(")
LEXEM(RBRACKET_ROUND, ")")
LEXEM(LBRACKET_SQUARE, "[")
LEXEM(RBRACKET_SQUARE, "]")
LEXEM(GR_THEN, ">")
LEXEM(LR_THEN, "<")
LEXEM(EQDEF, "\\eqdef")
LEXEM(RETURN, "\\exists!")
LEXEM(VAR_INIT, "\\exists")
LEXEM(FORALL, "\\forall")
LEXEM(IF,     "if")
LEXEM(CONDITION_RIGHT_ARROW, "\\Rightarrow")
LEXEM(PRINT, "see")
LEXEM(INPUT, "\\imath")
LEXEM(DOT, "\\nabla")
LEXEM(MOD,  "mod")
LEXEM(SHOW, "plot")