//lexem type, ID, keyword

LEXEM(OPERATOR, ADD , "+")
LEXEM(OPERATOR, SUB , "-")
LEXEM(OPERATOR, LR, ";")
LEXEM(OPERATOR, EQ, "=")
LEXEM(OPERATOR, LBRACKET_ROUND, "(")
LEXEM(OPERATOR, RBRACKET_ROUND, ")")
LEXEM(OPERATOR, LBRACKET_SQUARE, "[")
LEXEM(OPERATOR, RBRACKET_SQUARE, "]")
LEXEM(KEYWORD, VAR_INIT, "\\exists")
LEXEM(KEYWORD, CONDITION_RIGHT_ARROW, "\\Rightarrow")