//DEF_OPERATION(operation_name, operator, priority, tex_operator, tex_op_type)

DEF_OPERATION(ADD, "+", 0, "+", INFIX)
DEF_OPERATION(SUB, "-", 0, "-", INFIX)
DEF_OPERATION(MUL, "*", 1, "\\cdot", INFIX)
DEF_OPERATION(DIV, "/", 1, "\\frac", PREFIX)
DEF_OPERATION(SIN, "sin", 2, "\\sin", PREFIX)
DEF_OPERATION(COS, "cos", 2, "\\cos", PREFIX)
DEF_OPERATION(LOG, "log", 2, "log", INFIX)
DEF_OPERATION(LN,  "ln", 2, "ln", INFIX)
DEF_OPERATION(EXP, "^", 2, "^", INFIX)
DEF_OPERATION(TAN, "tg", 2, "tg", INFIX)
DEF_OPERATION(COT, "ctg", 2, "ctg", INFIX)
DEF_OPERATION(ATAN, "arctg", 2, "arctg", INFIX)
DEF_OPERATION(ACOT, "arcctg", 2, "arcctg", INFIX)
DEF_OPERATION(ACOS, "arccos", 2, "arccos", INFIX)
DEF_OPERATION(ASIN, "arcsin", 2, "arcsin", INFIX)